version: "3"
containers:
- name: guac
  image: gcr.io/instruqt/guacamole
  shell: /bin/bash
  ports:
  - 8080
virtualmachines:
- name: es3-api
  image: elastic/debian12nginx128
  shell: /bin/bash
  environment:
    PRODUCT_TIER: complete
    PROJECT_TYPE: observability
    REGIONS: aws-us-east-1
  memory: 4096
  cpus: 1
  provision_ssl_certificate: true
  allow_external_ingress:
  - high-ports
- name: k3s
  image: elastic/k3s-v1-33-4
  shell: /bin/bash
  memory: 24576
  cpus: 4
- name: windows
  image: instruqt/windows-server
  machine_type: n1-standard-4
secrets:
- name: ESS_CLOUD_API_KEY
