---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wiki-route
  namespace: wiki
spec:
  entryPoints:
    - wiki
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      services:
        - name: wiki
          port: 80
      middlewares:
        - name: basic-auth-middleware
          namespace: traefik
---
apiVersion: batch/v1
kind: Job
metadata:
  name: wikijs-config
  namespace: wiki
spec:
  backoffLimit: 0 
  template:
    spec:
      containers:
        - image: $repo/wikijs:$course
          name: wikijs
          imagePullPolicy: Always
          args:
            - "--action"
            - "wiki_config"
            - "--wiki_public_url"
            - "http://wiki.wiki.svc.cluster.local:80"
            - "--wiki_private_url"
            - "http://wiki.wiki.svc.cluster.local:80"
      restartPolicy: Never
---
