---
apiVersion: v1
kind: Service
metadata:
  name: wiki-ext
  namespace: wiki
spec:
  ports:
    - name: wiki
      port: 9082
      protocol: TCP
      targetPort: http
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: wiki
    app.kubernetes.io/name: wiki
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wiki
  namespace: wiki
spec:
  rules:
  - http:
      paths:
      - path: /wiki
        pathType: ImplementationSpecific
        backend:
          service:
            name: wiki
            port:
              number: 3000
---
apiVersion: batch/v1
kind: Job
metadata:
  name: wikijs-config22
  namespace: wiki
spec:
  backoffLimit: 0 
  template:
    spec:
      containers:
        - image: $repo/wikijs:$course
          name: wikijs
          imagePullPolicy: Always
          args:
            - "--action"
            - "wiki_config"
            - "--wiki_public_url"
            - "http://wiki.wiki.svc.cluster.local:80"
            - "--wiki_private_url"
            - "http://wiki.wiki.svc.cluster.local:80"
      restartPolicy: Never
---
