version: "1"
name: hello_world
enabled: true
tags:
- training

inputs:
  - name: username
    type: string
    required: true
    description: "The name of the user to greet"

triggers:
  - type: manual

steps:
  - name: print_greeting
    type: console
    with:
      message: "Hello, {{ inputs.username }}!"