version: "1"
name: ip_geolocator
description: "Geolocate an IP address using a public API"
enabled: true
tags:
- training

consts:
  ip_api_base_url: http://ip-api.com/json

inputs:
  - name: ip_address
    type: string
    required: true
    description: "The IP to geolocate (e.g., 8.8.8.8)"

triggers:
  - type: manual

steps:
  - name: get_geolocation
    type: http
    with:
      url: "{{ consts.ip_api_base_url }}/{{ inputs.ip_address }}"
      method: GET

  - name: print_location
    type: console
    with:
      message: "IP {{ inputs.ip_address }} is in {{ steps.get_geolocation.output.data.city }}, {{ steps.get_geolocation.output.data.country }}."