version: '1'
name: a2a
description: Allows agent to agent communication
enabled: true
triggers:
- type: manual
  inputs:
  - name: mode
    description: mode=list to list available agents, mode=describe to get the metadata associated with a specific agent, mode=execute to call another agent
    required: true
    default: create
    type: string
  - name: agentId
    description: the id of the agent to call (required for mode=describe and mode=execute)
    required: false
    type: string
  - name: body
    description: the JSON-RPC 2.0 A2A protocol body
    required: false
    type: string
settings:
  timeout: 20m

steps:
- name: mode_check
  type: switch
  expression: '{{ inputs.mode }}'
  cases:
  - match: list
    steps:
    - name: get_agents
      type: kibana.request
      with:
        method: GET
        path: /api/agent_builder/agents
  - match: describe
    steps:
    - name: describe
      type: kibana.request
      with:
        method: GET
        path: /api/agent_builder/a2a/{{ inputs.agentId }}.json
  - match: execute
    steps:
    - name: exec
      type: kibana.request
      with:
        method: POST
        path: /api/agent_builder/a2a/{{ inputs.agentId }}
        body: {{inputs.body}}

