name: alert_dequeue
enabled: true
description: dequeue alerts serially and start processing
tags:
- rca
triggers:
- type: scheduled
  with:
    every: 15s
steps:
- name: get_alert_process_id
  type: elasticsearch.request
  with:
    method: GET
    path: /workflow_config/_doc/alert_process

- name: alert_process_status
  type: kibana.request
  with:
    method: GET
    path: /api/workflowExecutions?workflowId={{ steps.get_alert_process_id.output._source.workflowId }}
    headers:
      x-elastic-internal-origin: kibana

- name: is_alert_process_running
  type: if
  condition: 'steps.alert_process_status.output.results[0].status : running'
  steps:
  - name: is_alert_process_running_debug1
    type: console
    with:
      message: workflow_alert_process running
  else:
  - name: is_alert_process_running_debug2
    type: console
    with:
      message: workflow_alert_process not running

  - name: dequeue_alerts
    type: elasticsearch.request
    with:
      method: GET
      path: /workflow_alert_queue/_search
      body:
        _source: true
        query:
          match_all: {}
        size: 1
        sort:
        - '@timestamp':
            order: asc

  - name: is_alert_pending
    type: if
    condition: steps.dequeue_alerts.output.hits.total.value > 0
    steps:
    - name: start_alert_process
      type: kibana.request
      with:
        method: POST
        path: /api/workflows/{{ steps.get_alert_process_id.output._source.workflowId }}/run
        body: '{ "inputs": {"event": {{steps.dequeue_alerts.output.hits.hits[0]._source.event | json }} } }'
        headers:
          x-elastic-internal-origin: kibana
    - name: mark_alert_handled
      type: elasticsearch.request
      with:
        method: DELETE
        path: /workflow_alert_queue/_doc/{{ steps.dequeue_alerts.output.hits.hits[0]._id }}
