name: case_dequeue
description: dequeue cases serially and start processing
enabled: true
consts:
  case_stable: 30s
tags:
- rca
triggers:
- type: scheduled
  with:
    every: 30s
steps:
- name: get_alert_process_id
  type: elasticsearch.request
  with:
    method: GET
    path: /workflow_config/_doc/alert_process

- name: alert_process_status
  type: kibana.request
  with:
    method: GET
    path: /api/workflowExecutions?workflowId={{ steps.get_alert_process_id.output._source.workflowId }}
    headers:
      x-elastic-internal-origin: kibana

- name: get_case_process_id
  type: elasticsearch.request
  with:
    method: GET
    path: /workflow_config/_doc/case_process

- name: case_process_status
  type: kibana.request
  with:
    method: GET
    path: /api/workflowExecutions?workflowId={{ steps.get_case_process_id.output._source.workflowId }}
    headers:
      x-elastic-internal-origin: kibana

- name: is_processing_running
  type: if
  condition: 'steps.alert_process_status.output.results[0].status : running or steps.case_process_status.output.results[0].status : running'
  steps:
  - name: is_processing_running_debug1
    type: console
    with:
      message: alert or case process running
  else:
  - name: is_processing_running_debug2
    type: console
    with:
      message: alert or case process not running

  - name: dequeue_case
    type: elasticsearch.request
    with:
      method: POST
      path: /workflow_case_queue/_search
      body:
        _source: true
        query:
          match_all: {}
        size: 1
        sort:
        - '@timestamp':
            order: asc

  - name: is_case_pending
    type: if
    condition: steps.dequeue_case.output.hits.total.value > 0
    steps:

    - name: is_case_stable
      type: if
      condition: steps.dequeue_case.output.hits.hits[0]._source.@timestamp < now-{{ consts.case_stable }}
      steps:

      - name: start_case_process
        type: kibana.request
        with:
          method: POST
          path: /api/workflows/{{ steps.get_case_process_id.output._source.workflowId }}/run
          body: '{ "inputs": {"case_id": "{{steps.dequeue_case.output.hits.hits[0]._source.case_id }}" } }'
          headers:
            x-elastic-internal-origin: kibana
      - name: mark_case_handled
        type: elasticsearch.request
        with:
          method: POST
          path: /workflow_case_queue/_delete_by_query
          body:
            query:
              match:
                case_id: '{{ steps.dequeue_case.output.hits.hits[0]._source.case_id }}'

