version: '1'
name: get_case_alerts
description: Get Alerts Attached to a Case
enabled: true
tags:
- rca
triggers:
- type: manual
inputs:
- name: case_id
  description: the case ID
  type: string
  required: true
steps:
- name: get_alerts
  type: kibana.request
  with:
    method: GET
    path: /api/cases/{{ inputs.case_id }}/alerts
