version: '1'
name: identify_entity_by_service_name
description: Identify an entity by its service name
enabled: true
tags:
- rca
triggers:
- type: manual
inputs:
- name: service_name
  description: the name of the service
  required: true
  type: string
- name: search_start_time
  description: the end of the time window (Format as `%Y-%m-%dT%H:%M:%SZ`)
  type: string
- name: search_end_time
  description: the end of the time window (Format as `%Y-%m-%dT%H:%M:%SZ`)
  type: string
steps:

- name: get_exemplary_log_lines
  type: elasticsearch.esql.query
  with:
    query: FROM logs-* | WHERE @timestamp >= "{{ inputs.search_start_time }}" AND @timestamp <= "{{ inputs.search_end_time }}" | WHERE service.name == "{{ inputs.service_name }}" | STATS pattern_count = COUNT() BY pattern = CATEGORIZE(message) | WHERE pattern IS NOT NULL | SORT pattern_count DESC | KEEP pattern | LIMIT 10
    format: json

- name: identify_log_stream
  type: ai.prompt
  with:
    prompt: |
      Identify if this is a custom or a well-known service by the exemplary log lines provided. 
      * If it is a custom application, output a field `service.type` with a value of `custom`
      * If it is a well-known service (like a database or a proxy), output a field `service.type` with a value of the identified service type (e.g., `postgresql` or `nginx`)
      ```logs
      {{ steps.get_exemplary_log_lines.output.values | json }}
      ```
      * Respond only in valid JSON format with no newlines, no extra spaces, and with no prefixes or postfixes (DO NOT USE ```json prefix and ``` postfix) in your response!'
- name: output
  type: console
  with:
    message: '{{ steps.identify_log_stream.output.content }}'
