#!/bin/bash
set -euxo pipefail

echo "Running track setup script on host es3-api-v1"

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# ----------------------------------------- CLONE CODE

export INSTRUQT_TRACK_SLUG=o11y--course--field--100-e2e--main
export REPO=us-central1-docker.pkg.dev/elastic-sa/tbekiares
export GITHUB_REPO=https://github.com/ty-elastic/instruqt_$INSTRUQT_TRACK_SLUG

mkdir -p /workspace/workshop
git clone $GITHUB_REPO /workspace/workshop
cd /workspace/workshop

# ----------------------------------------- SETUP SERVERLESS

source /workspace/workshop/instruqt/scripts/serverless/create.sh

source /workspace/workshop/instruqt/scripts/genai.sh
source /workspace/workshop/instruqt/scripts/workflow.sh
source /workspace/workshop/instruqt/scripts/streams.sh
