apiVersion: v1
kind: ConfigMap
metadata:
  name: windows-user-mapping
  namespace: infra
data:
  user-mapping.xml: |
    <user-mapping>
      <!-- Define the Guacamole web UI admin credentials -->
      <authorize username="traefik">
        <connection name="Windows Server">
          <protocol>rdp</protocol>
          <param name="hostname">$WINDOWS_HOST</param> 
          <param name="port">3389</param>
          <param name="username">$WINDOWS_HOST_USERNAME</param>
          <param name="password">$WINDOWS_HOST_PASSWORD</param>
          <param name="security">nla</param>
          <param name="ignore-cert">true</param>
        </connection>
      </authorize>
    </user-mapping>
---
apiVersion: v1
kind: Pod
metadata:
  name: windows
  namespace: infra
  labels:
    service: windows
spec:
  volumes:
    - name: guac-config-volume
      configMap:
        name: windows-user-mapping
  serviceAccountName: guacamole-sa # Crucial for auto-auth
  containers:
    # 1. Guacamole Web Application
    - name: guacamole-client
      image: guacamole/guacamole:latest
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: GUACD_HOSTNAME
          value: "localhost"
        - name: GUACD_PORT
          value: "4822"
        - name: GUACAMOLE_HOME
          value: "/etc/guacamole"
        - name: HTTP_AUTH_ENABLED
          value: "true"
        - name: "HTTP_AUTH_HEADER"
          value: "X-Windows-User"
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
      volumeMounts:
        - name: guac-config-volume
          mountPath: /etc/guacamole
    # 2. Guacamole Protocol Daemon (Sidecar)
    - name: guacd
      image: guacamole/guacd:latest
      ports:
        - containerPort: 4822
          protocol: TCP
      volumeMounts:
        - name: guac-config-volume
          mountPath: /etc/guacamole/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: windows
  name: windows
  namespace: infra
spec:
  ports:
    - name: windows
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  sessionAffinity: ClientIP 
  selector:
    service: windows
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: guac-auth-header
  namespace: infra
spec:
  headers:
    customRequestHeaders:
      X-Windows-User: "traefik"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: windows-route
  namespace: infra
spec:
  entryPoints:
    - windows
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      services:
        - name: windows
          port: 8080
      middlewares:
        - name: basic-auth-middleware
          namespace: traefik
        - name: guac-auth-header
          namespace: infra