#!/bin/bash
set -euxo pipefail
set +x

wait_for_instruqt_bootstrap() {
    # Wait for the Instruqt host bootstrap to finish
    until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
    do
        sleep 1
    done
}

wait_for_kubernetes_api() {
    # Wait for the Kubernetes API server to become available
    while ! curl --silent --fail --output /dev/null http://localhost:8001/api
    do
        sleep 1
    done
}

setup_bash_shell() {
    # Enable bash completion for kubectl
    echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc
    echo "complete -F __start_kubectl k" >> /root/.bashrc
}


# Wait for the Instruqt host bootstrap to finish
wait_for_instruqt_bootstrap

# Set up bash shell
setup_bash_shell

# Wait for the Kubernetes API server to become available
wait_for_kubernetes_api

# ----------------------------------------- CLONE CODE

export COURSE=o11y--course--field--100-e2e
export GITHUB_REPO=https://github.com/ty-elastic/instruqt_$COURSE--main

mkdir -p /workspace/workshop
git clone $GITHUB_REPO /workspace/workshop
cd /workspace/workshop

# ----------------------------------------- DEPS

# sudo apt-get update
# sudo apt-get -y install podman

# ----------------------------------------- APPS

source /workspace/workshop/instruqt/scripts/wait_on_es.sh
source /workspace/workshop/instruqt/scripts/vars.sh

#source /workspace/workshop/instruqt/scripts/synthetics.sh

echo "Configuring OTel"
output=$(curl -s -X POST "$KIBANA_URL/internal/observability_onboarding/kubernetes/flow" \
      --header 'Content-Type: application/json' \
      --header "Authorization: Basic $ELASTICSEARCH_AUTH_BASE64" \
      --header 'kbn-xsrf: true' \
      --header 'x-elastic-internal-origin: Kibana' \
      --data '{"pkgName": "kubernetes_otel"}')

OTEL_API_KEY=$(echo $output | jq -r '.apiKeyEncoded')
echo $OTEL_API_KEY
OTEL_MANAGED_OTLP_SERVICE_URL=$(echo $output | jq -r '.managedOtlpServiceUrl')
echo $OTEL_MANAGED_OTLP_SERVICE_URL

cd /workspace/workshop
./build.sh -o serverless -c $COURSE -d true -b false -s all -j $ELASTICSEARCH_URL -i $ELASTICSEARCH_APIKEY -k $OTEL_MANAGED_OTLP_SERVICE_URL
