#!/bin/bash
set -euxo pipefail
set +x

echo "Running track setup script on host es3-api-v1"

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# ----------------------------------------- CLONE CODE

export COURSE=o11y--course--field--100-e2e
export GITHUB_REPO=https://github.com/ty-elastic/instruqt_$COURSE--main

mkdir -p /workspace/workshop
git clone --filter=blob:none --no-checkout $GITHUB_REPO /workspace/workshop
cd /workspace/workshop
git sparse-checkout init
git sparse-checkout set instruqt/scripts
git checkout main

# ----------------------------------------- SETUP SERVERLESS

source /workspace/workshop/instruqt/scripts/serverless/create.sh

source /workspace/workshop/instruqt/scripts/wait_on_es.sh
source /workspace/workshop/instruqt/scripts/vars.sh

source /workspace/workshop/instruqt/scripts/genai.sh
source /workspace/workshop/instruqt/scripts/workflow.sh
source /workspace/workshop/instruqt/scripts/streams.sh

source /workspace/workshop/instruqt/scripts/integrations.sh
