#!/bin/bash
#set -euxo pipefail
set +x

wait_for_instruqt_bootstrap() {
    # Wait for the Instruqt host bootstrap to finish
    until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
    do
        sleep 1
    done
}

wait_for_kubernetes_api() {
    # Wait for the Kubernetes API server to become available
    while ! curl --silent --fail --output /dev/null http://localhost:8001/api
    do
        sleep 1
    done
}

setup_bash_shell() {
    # Enable bash completion for kubectl
    echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc
    echo "complete -F __start_kubectl k" >> /root/.bashrc
}

check_host() {
    if host "$1" > /dev/null; then
        echo "host reachable"
        return 0
    else
        echo "host not yet reachable"
        return 1
    fi
}

strip_hostname() {
    local url="${1#*://}"  # Remove protocol (http:// or https://)
    url="${url%%/*}"       # Remove trailing paths (everything after /)
    url="${url%%:*}"       # Remove port (everything after :)
    echo "$url"
}

# Wait for the Instruqt host bootstrap to finish
wait_for_instruqt_bootstrap

# Set up bash shell
setup_bash_shell

# Wait for the Kubernetes API server to become available
wait_for_kubernetes_api

# ----------------------------------------- CLONE CODE

export COURSE=o11y--course--field--100-e2e
export REPO=us-central1-docker.pkg.dev/elastic-sa/tbekiares
export GITHUB_REPO=https://github.com/ty-elastic/instruqt_$COURSE--main

mkdir -p /workspace/workshop
git clone $GITHUB_REPO /workspace/workshop
cd /workspace/workshop

# ----------------------------------------- APPS

source /workspace/workshop/instruqt/scripts/wait_on_es.sh
source /workspace/workshop/instruqt/scripts/vars.sh

FLEET_URL_NO_PREFIX=$(strip_hostname $FLEET_URL)
retry_command_lin check_host $FLEET_URL_NO_PREFIX
source /workspace/workshop/instruqt/scripts/synthetics.sh

INGEST_URL_NO_PREFIX=$(strip_hostname $INGEST_URL)
retry_command_lin check_host $INGEST_URL_NO_PREFIX
cd /workspace/workshop
./build.sh -o serverless -c $COURSE -d true -b false -s all -j $ELASTICSEARCH_URL -i $ELASTICSEARCH_APIKEY -k $INGEST_URL:443 -w true
