#!/bin/bash
#set -euxo pipefail
set +x

echo "Running track setup script on host es3-api-v1"

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# ----------------------------------------- CLONE CODE

export COURSE=o11y--course--field--100-e2e
export ARTIFACTS=elastic-sa/locations/us-central1/repositories/tbekiares-instruqt

mkdir -p /workspace/workshop
cd /workspace/workshop

curl -X GET \
     -o $COURSE.tgz \
     "https://artifactregistry.googleapis.com/download/v1/projects/$ARTIFACTS/files/$COURSE%3A1.0%3A$COURSE.tgz:download?alt=media"
tar -xvzf $COURSE.tgz

# ----------------------------------------- SETUP SERVERLESS

source /workspace/workshop/instruqt/scripts/serverless/create.sh

# ----------------------------------------- APPS

source /workspace/workshop/instruqt/scripts/vars.sh -w true

cd /workspace/workshop

# platform
./build.sh -o false -c $COURSE -d false -b false -s none -j $ELASTICSEARCH_URL -h $KIBANA_URL -i $ELASTICSEARCH_APIKEY -k $INGEST_URL:443 -f true
