apiVersion: v1
kind: ServiceAccount
metadata:
  name: profiling-collector
  namespace: opentelemetry-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: profiling-collector
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: profiling-collector
subjects:
- kind: ServiceAccount
  name: profiling-collector
  namespace: opentelemetry-operator-system
roleRef:
  kind: ClusterRole
  name: profiling-collector
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: profiling-collector-config
  namespace: opentelemetry-operator-system
data:
  config.yaml: |-
    receivers:
      profiling: {}

    connectors:
      profilingmetrics: {}

    processors:
      resource/environment:
        attributes:
          - key: deployment.environment.name
            from_attribute: k8s.namespace.name
            action: upsert
          - key: data_stream.namespace
            from_attribute: k8s.namespace.name
            action: upsert
          - key: resource.attributes.cloud.region
            from_attribute: k8s.namespace.name
            action: upsert

      resource/hostname:
        attributes:
          - key: host.name
            value: "${env:OTEL_K8S_NODE_NAME}"
            action: upsert
          - key: k8s.node.name
            value: "${env:OTEL_K8S_NODE_NAME}"
            action: upsert    
      k8sattributes:
        passthrough: false
        pod_association:
          - sources:
              - from: resource_attribute
                name: container.id
        extract:
          metadata:
          - "k8s.namespace.name"
          - "k8s.pod.name"
          - "k8s.pod.ip"
          - "k8s.pod.uid"
          - "k8s.pod.start_time"
          - k8s.container.name
          - container.id
          - container.image.name
          - container.image.tag
          - "service.name"
          - "service.version"
          - "service.instance.id"

    exporters:
      debug:
        verbosity: basic
      otlp/gateway:
        endpoint: "http://opentelemetry-kube-stack-daemon-collector.opentelemetry-operator-system.svc.cluster.local:4317"
        tls:
          insecure: true

    service:
      pipelines:
        profiles:
          receivers: [ profiling ]
          processors:
            - k8sattributes
            - resource/hostname
            - resource/environment
          exporters: [ profilingmetrics ]
        metrics:
          receivers: [ profilingmetrics ]
          exporters: [ debug, otlp/gateway ]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: profiling-collector
  namespace: opentelemetry-operator-system
spec:
  selector:
    matchLabels:
      app: profiling-collector
  template:
    metadata:
      labels:
        app: profiling-collector
    spec:
      serviceAccountName: profiling-collector
      containers:
        - name: collector
          image: docker.elastic.co/elastic-agent/elastic-agent:9.4.0-SNAPSHOT
          env:
            - name: OTEL_K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - "elastic-agent"
            - "otel"
            - "--config=/etc/otelcol/config.yaml"
            - "--feature-gates=service.profilesSupport"
          volumeMounts:
            - mountPath: /etc/otelcol/config.yaml
              name: data
              subPath: config.yaml
              readOnly: true
            - name: debugfs
              mountPath: /sys/kernel/debug
              readOnly: true
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            privileged: true
            #procMount: "Unmasked"
            capabilities:
              add:
                - SYS_ADMIN
      #hostUsers: false
      hostPID: true
      restartPolicy: Always
      volumes:
        - name: data
          configMap:
            name: profiling-collector-config
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
            type: Directory