version: '1'
name: alert_process
description: Process o11y alerts and correlate to cases
enabled: true
tags:
- rca
consts:
  workflow_name: alert_process
  case_workflow_name: case_process
triggers:
- type: manual
settings:
  timeout: 20m
steps:
- name: workflow_status
  type: kibana.request
  with:
    method: GET
    path: /api/workflows/workflow/{{ workflow.id }}/executions
    headers:
      x-elastic-internal-origin: kibana
- name: is_workflow_running
  type: if
  condition: 'steps.workflow_status.output.results[1].status : running'
  steps:
  - name: is_workflow_running_debug
    type: console
    with:
      message: workflow running
  else:
  - name: get_active_alerts
    type: kibana.request
    with:
      method: POST
      path: /internal/rac/alerts/find
      headers:
        x-elastic-internal-origin: Kibana
      body:
        consumers: [apm, infrastructure, logs, uptime, slo, observability, alerts]
        query:
          bool:
            must:
            - range:
                '@timestamp':
                  gte: now-24h/h
            - term:
                kibana.alert.status: active
            - term:
                tags: rca
            must_not:
            - exists:
                field: kibana.alert.case_ids

  - name: foreach_alert
    type: foreach
    foreach: '{{ steps.get_active_alerts.output.hits.hits }}'
    steps:


      - name: correlate
        type: ai.agent
        create-conversation: true
        agent-id: rca
        with:
          schema:
            title: CorrelateAlert
            type: object
            additionalProperties: false
            required: [case_id, relation]
            properties:
              case_id:
                type: string
                description: if this alert is related to an existing case, the ID of the related case, otherwise `NONE`
              relation:
                type: string
                description: if this alert is related to an existing case, briefly explain how this alert relates to the identified case, otherwise briefly explain why it isn't related to existing cases
              title:
                type: string
                description: if this alert is not related to an existing case, briefly summarize the attached alert in a few words
              trigger:
                type: string
                description: if this alert is not related to an existing case, a detailed summary of the attached alert
              severity:
                type: string
                description: if this alert is not related to an existing case, a value of `low`, `medium`, `high`, or `critical` based on an initial analysis of the alert
              system_environment:
                type: string
                description: if, from the topologies, you can identify a system_environment associated with this alert, a value of the name of the associated system
          message: |
            Try to correlate this alert to a case: 
            ```json
            {{ steps.get_active_alerts.output.hits.hits[foreach.index]._source | json: 2 }}
            ```
      - name: new_or_update_case
        type: if
        condition: 'steps.correlate.output.structured_output.case_id : NONE'
        steps:
          - name: create_new_case
            type: cases.createCase
            connector-id: snowem
            with:
              title: '{{ steps.correlate.output.structured_output.title }}'
              description: '{{ steps.correlate.output.structured_output.trigger }}'
              severity: '{{ steps.correlate.output.structured_output.severity }}'
              tags: ["rca"]
              owner: "observability"
              settings:
                syncAlerts: true
              customFields:
                - key: system_environment
                  type: text
                  value: '{{ steps.correlate.output.structured_output.system_environment}}'
            
      - name: case_id
        type: console
        with:
          message: "{% if steps.correlate.output.structured_output.case_id == 'NONE' %}{{ steps.create_new_case.output.case.id }}{% else %}{{ steps.correlate.output.structured_output.case_id }}{%endif%}"

      - name: add_alert_to_case
        type: cases.addAlerts
        with:
          case_id: '{{ steps.case_id.output }}'
          alerts:
            - alertId: '{{ steps.get_active_alerts.output.hits.hits[foreach.index]._id }}'
              index: '{{ steps.get_active_alerts.output.hits.hits[foreach.index]._index }}'
        on-failure:
          retry:
            max-attempts: 2
            delay: 1s

      - name: add_comment_to_case
        type: cases.addComment
        with:
          case_id: '{{ steps.case_id.output }}'
          comment: |
              # Related Alert
              * Summary: {{ steps.get_active_alerts.output.hits.hits[foreach.index]._source["kibana.alert.reason"] }}
              * [Conversation](/app/agent_builder/conversations/{{ steps.correlate.output.conversation_id }})
              * Relationship to Case: {{ steps.correlate.output.structured_output.relation }}
        on-failure:
          retry:
            max-attempts: 2
            delay: 1s

  - name: if_new_alerts
    type: if
    condition: steps.get_active_alerts.output.hits.total.value > 0
    steps:
      - name: get_case_workflow_id
        type: console
        with:
          message: '{% for workflow in steps.get_workflows.output.results %}{%- if workflow.name == consts.case_workflow_name -%}{{ workflow.id }}{% break %}{%- endif -%}{% endfor %}'
      - name: start_case_process_workflow
        type: workflow.executeAsync
        with:
          workflow-id: "{{ steps.get_case_workflow_id.output }}"
          inputs:
            alerts_ready: true
            event: ''