version: '1'
name: create_case
description: Create new case
enabled: true
tags:
- rca
triggers:
- type: manual
settings:
  timeout: 20m
inputs:
- name: description
  description: the description of the case
  required: true
  type: string
- name: title
  description: the title of the case
  required: true
  type: string
- name: severity
  description: the severity of the case
  required: true
  default: low
  type: string
steps:
  - name: get_case_settings
    type: kibana.request
    with:
      method: GET
      path: /api/cases/configure
  - name: create_new_case
    type: kibana.createCaseDefaultSpace
    with:
      connector:
        id: '{{ steps.get_case_settings.output.data[0].connector.id }}'
        name: '{{ steps.get_case_settings.output.data[0].connector.name }}'
        type: .none
        fields:
      description: '{{ inputs.description }}'
      owner: observability
      settings:
        syncAlerts: true
      severity: '{{ inputs.severity }}'
      tags:
      - trading
      title: '{{ inputs.title }}'
