version: '1'
name: get_topologies
description: Get System Topologies
enabled: true
tags:
- rca
triggers:
- type: manual
inputs:
- name: search_end_time
  description: the end of the time window (Format as `%Y-%m-%dT%H:%M:%SZ`)
  type: string
- name: system_environment
  description: System Environment
  required: false
  default: .*
  type: string
steps:
- name: get_system_topologies
  type: elasticsearch.request
  with:
    method: POST
    path: /workflow_topology/_search
    body:
      size: 0
      query:
        bool:
          filter:
          - range:
              '@timestamp':
                lte: '{{ inputs.search_end_time }}'
          - regexp:
              system_environment: '{{ inputs.system_environment }}'
      aggs:
        unique_field_buckets:
          terms:
            field: system_environment
            size: 100
            order:
              _key: asc
          aggs:
            latest_document:
              top_hits:
                size: 1
                sort:
                - '@timestamp':
                    order: desc
                _source:
                  includes:
                  - '@timestamp'
                  - system_environment
                  - topology
- name: foreach_topology
  type: foreach
  foreach: '{{ steps.get_system_topologies.output.aggregations.unique_field_buckets.buckets }}'
  steps:
  - name: output
    type: console
    with:
      message: '{{ foreach.item.latest_document.hits.hits[0]._source | json}}'
