name: remediation_service_action
enabled: true
consts:
  remote_host: http://host-1:43210
tags:
- rca
inputs:
- name: service_name
  type: string
- name: service_action
  type: string
- name: case_id
  type: string
  default: NOT_AVAILABLE
triggers:
- type: manual
steps:
- name: call_remote
  type: http
  with:
    url: '{{consts.remote_host}}/service/{{inputs.service_name}}/{{inputs.service_action}}'
    method: POST
    headers:
      Content-Type: application/json

- name: add_comment_to_existing_case
  type: kibana.request
  with:
    method: POST
    path: /api/cases/{{ inputs.case_id }}/comments
    body:
      type: user
      owner: observability
      comment: ⚡ Attempted `{{inputs.service_action}}` of `{{inputs.service_name}}`
  on-failure:
    continue: true
