apiVersion: batch/v1
kind: Job
metadata:
  name: assets-$JOB_ID
spec:
  template:
    spec:
      hostNetwork: true
      containers:
        - image: $REPO/assets:$COURSE
          name: assets
          imagePullPolicy: Always
          command:
            - "python"
            - "/python-docker/app.py"
            - "--kibana_host"
            - "$elasticsearch_kibana_endpoint"
            - "--es_host"
            - "$elasticsearch_es_endpoint"    
            - "--es_apikey"
            - "$elasticsearch_api_key"    
            - "--remote_host"
            - "$remote_endpoint" 
            - "load"
      restartPolicy: Never
---

