---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-connector
  labels:
    name: elastic-connector
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snow-elastic-connector-config
  namespace: elastic-connector
data:
  config.yml: |
    connectors:
    - 
      connector_id: "6O0OdZoBhV9yxq76y715"
      service_type: "servicenow"
      api_key: "NmUwT2Rab0JoVjl5eHE3Nnk3Mzg6dDBZZDZFa24zV0FGU3VySGk2OEZfdw=="
    elasticsearch:
      host: "https://bdcdd46669324fe4bf014ca076d36cdb.us-west2.gcp.elastic-cloud.com:443"
      api_key: "NmUwT2Rab0JoVjl5eHE3Nnk3Mzg6dDBZZDZFa24zV0FGU3VySGk2OEZfdw=="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snow-elastic-connector
  namespace: elastic-connector
  labels:
    service: snow-elastic-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      service: snow-elastic-connector
  template:
    metadata:
      annotations:
        io.opentelemetry.discovery.logs/enabled: "false"
      labels:
        service: snow-elastic-connector
    spec:
      containers:
        - name: elastic-connector
          image: docker.elastic.co/integrations/elastic-connectors:9.3.0-SNAPSHOT
          imagePullPolicy: Always
          command:
            - "/app/bin/elastic-ingest"
            - "-c"
            - "/config/config.yml"
          volumeMounts:
            - mountPath: /config/config.yml
              name: data
              subPath: config.yml
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: data
          configMap:
            name: snow-elastic-connector-config
---
