consts:
  ai_connector: Elastic-Managed-LLM
  ai_proxy: 
    https://tbekiares-demo-aiassistantv2-1059491012611.us-central1.run.app
  ai_timeout: 10m
  es_host: https://snap-ae8a92.es.us-west2.gcp.elastic-cloud.com
  kbn_auth: ApiKey OEpsYkY1b0JyVktacWxPV1VITGo6Z2d2MmRZYXdTQkpOZ1dhMmVXYmo0Zw==
  kbn_host: https://snap-ae8a92.kb.us-west2.gcp.elastic-cloud.com
name: alert_dequeue
enabled: true
description: dequeue alerts serially and start processing
tags:
- automated_observability_triage
triggers:
- type: manual
steps:
- name: get_alert_process_id
  type: http
  with:
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
    method: GET
    timeout: 30s
    url: '{{ consts.es_host }}/workflow_config/_doc/alert_process_workflow'
- name: alert_process_status
  type: http
  with:
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
      kbn-xsrf: true
      x-elastic-internal-origin: kibana
    method: GET
    url: '{{ consts.kbn_host }}/api/workflowExecutions?workflowId={{ steps.get_alert_process_id.output.data._source.workflow_id }}'
- name: is_alert_process_running
  type: if
  condition: 'steps.alert_process_status.output.status : completed'
  steps:
  - name: is_alert_process_running_debug1
    type: console
    with:
      message: workflow_alert_process running
  else:
  - name: is_alert_process_running_debug2
    type: console
    with:
      message: workflow_alert_process not running
  - name: dequeue_alerts
    type: http
    with:
      body:
        _source: true
        query:
          match_all:
        size: 1,
      headers:
        Authorization: '{{ consts.kbn_auth }}'
        Content-Type: application/json
      method: GET
      url: '{{ consts.es_host }}/workflow_alert_queue/_search'
  - name: is_new_alert
    type: if
    condition: 'steps.dequeue_alerts.output.data.hits.hits[0]._source.alerts.new.count : *'
    steps:
    - name: start_alert_process
      type: http
      with:
        body: '{ "inputs": {"event": {"alerts": {{steps.dequeue_alerts.output.data.hits.hits[0]._source.alerts.new.data | json }} } } }'
        headers:
          Authorization: '{{ consts.kbn_auth }}'
          Content-Type: application/json
          kbn-xsrf: true
          x-elastic-internal-origin: kibana
        method: POST
        url: '{{ consts.kbn_host }}/api/workflows/{{ steps.get_alert_process_id.output.data._source.workflow_id }}/run'
    else:
    - name: start_alert_process2
      type: http
      with:
        body: '{ "inputs": {"event": {{ steps.dequeue_alerts.output.data.hits.hits[0]._source | json }} } }'
        headers:
          Authorization: '{{ consts.kbn_auth }}'
          Content-Type: application/json
          kbn-xsrf: true
          x-elastic-internal-origin: kibana
        method: POST
        url: '{{ consts.kbn_host }}/api/workflows/{{ steps.get_alert_process_id.output.data._source.workflow_id }}/run'
  - name: mark_alert_handled
    type: http
    with:
      headers:
        Authorization: '{{ consts.kbn_auth }}'
        Content-Type: application/json
      method: DELETE
      url: '{{ consts.es_host }}/workflow_alert_queue/_doc/{{ steps.dequeue_alerts.output.data.hits.hits[0]._id }}'
