consts:
  ai_connector: Elastic-Managed-LLM
  ai_proxy: 
    https://tbekiares-demo-aiassistantv2-1059491012611.us-central1.run.app
  ai_timeout: 10m
  es_host: https://snap-ae8a92.es.us-west2.gcp.elastic-cloud.com
  kbn_auth: ApiKey OEpsYkY1b0JyVktacWxPV1VITGo6Z2d2MmRZYXdTQkpOZ1dhMmVXYmo0Zw==
  kbn_host: https://snap-ae8a92.kb.us-west2.gcp.elastic-cloud.com
name: alert_queue
enabled: true
version: '1'
description: ingest alerts
tags:
- automated_observability_triage
triggers:
- type: alert
  enabled: true
steps:
- name: alert_debug
  type: console
  with:
    message: '{{ event | json }}'
- name: queue_alert
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_alert_queue/_doc'
    method: POST
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
    body: '{{event | json}}'
    timeout: 30s
