name: alert_dequeue
description: dequeue alerts serially and start processing
enabled: true
tags:
  - automated_observability_triage
triggers:
  - type: manual
steps:
  - name: get_alert_process_id
    type: http
    with:
      url: "{{ consts.es_host }}/workflow_config/_doc/alert_process_workflow"
      method: GET
      headers:
        Content-Type: application/json
        Authorization: "{{ consts.kbn_auth }}"
      timeout: 30s
  - name: alert_process_status
    type: http
    with:
      url: "{{ consts.kbn_host }}/api/workflowExecutions?workflowId={{ steps.get_alert_process_id.output.data._source.workflow_id }}"
      method: "GET"
      headers:
        x-elastic-internal-origin: kibana
        kbn-xsrf: true
        Content-Type: application/json
        Authorization: "{{ consts.kbn_auth }}"
  - name: is_alert_process_running
    type: if
    condition: "steps.alert_process_status.output.status : completed"
    # found
    steps:
      - name: is_alert_process_running_debug1
        type: console
        with:
          message: "workflow_alert_process running"
    else:
      - name: is_alert_process_running_debug2
        type: console
        with:
          message: "workflow_alert_process not running"

      - name: dequeue_alerts
        type: http
        with:
          url: "{{ consts.es_host }}/workflow_alert_queue/_search"
          method: "GET"
          body:
            "size": 1, 
            "query":
              "match_all":
            "_source": true
          headers:
            Content-Type: application/json
            Authorization: "{{ consts.kbn_auth }}"

      - name: is_new_alert
        type: if
        condition: "steps.dequeue_alerts.output.data.hits.hits[0]._source.alerts.new.count : *"
        steps:
        - name: start_alert_process
          type: http
          with:
            url: "{{ consts.kbn_host }}/api/workflows/{{ steps.get_alert_process_id.output.data._source.workflow_id }}/run"
            method: "POST"
            body: '{ "inputs": {"event": {"alerts": {{steps.dequeue_alerts.output.data.hits.hits[0]._source.alerts.new.data | json() }} } } }'
            headers:
              x-elastic-internal-origin: kibana
              kbn-xsrf: true
              Content-Type: application/json
              Authorization: "{{ consts.kbn_auth }}"
        else:
        - name: start_alert_process2
          type: http
          with:
            url: "{{ consts.kbn_host }}/api/workflows/{{ steps.get_alert_process_id.output.data._source.workflow_id }}/run"
            method: "POST"
            body: '{ "inputs": {"event": {{steps.dequeue_alerts.output.data.hits.hits[0]._source | json() }} } }'
            headers:
              x-elastic-internal-origin: kibana
              kbn-xsrf: true
              Content-Type: application/json
              Authorization: "{{ consts.kbn_auth }}"

      - name: mark_alert_handled
        type: http
        with:
          url: "{{ consts.es_host }}/workflow_alert_queue/_doc/{{steps.dequeue_alerts.output.data.hits.hits[0]._id}}"
          method: "DELETE"
          headers:
            Content-Type: application/json
            Authorization: "{{ consts.kbn_auth }}"

consts:
  ai_timeout: 10m
  ai_connector: "Elastic-Managed-LLM"
  ai_proxy: https://tbekiares-demo-aiassistant-1059491012611.us-central1.run.app
  kbn_host: https://581b85187ee040c3bc41f917001ef0b7.us-west2.gcp.elastic-cloud.com
  es_host: https://eb9be4b1f8e94c2fb951189307a03646.us-west2.gcp.elastic-cloud.com
  kbn_auth: ApiKey U1ZyZjdaa0I4eVREU3ZXeGx6bm06cnRpNUhkMldyYlQ1NjNaTGt5UExJQQ==