description: Process o11y alerts and correlate to cases
enabled: true
name: alert_process
tags:
- rca
triggers:
- type: alert
- type: manual
settings:
  timeout: 20m
version: '1'
steps:
- name: foreach_alert
  type: foreach
  foreach: '{{ event.alerts }}'
  steps:
  - name: correlate
    type: kibana.request
    with:
      method: POST
      path: /api/agent_builder/converse
      headers:
        kbn-xsrf: 'true'
      body:
        agent_id: alert_correlation
        input: 'try to correlate this alert: {{ foreach.item | json }}. Respond only in valid JSON format with no newlines, no extra spaces, and with no prefixes or postfixes (DO NOT USE ```json prefix and ``` postfix) in your response!'

  - name: correlate_parse
    type: console
    with:
      message: ${{ steps.correlate.output.response.message | json_parse }}

  - name: new_or_update_case
    type: if
    condition: 'steps.correlate_parse.output.case_id : NONE'
    steps:

    - name: get_case_settings
      type: kibana.request
      with:
        method: GET
        path: /api/cases/configure

    - name: create_new_case
      type: kibana.createCaseDefaultSpace
      with:
        connector:
          id: '{{ steps.get_case_settings.output.data[0].connector.id }}'
          name: '{{ steps.get_case_settings.output.data[0].connector.name }}'
          type: .none
          fields:
        customFields:
        - key: system_environment
          type: text
          value: '{{ steps.correlate_parse.output.system_environment}}'
        # - key: ai_conversation_id
        #   type: text
        #   value: '{{ steps.correlate.output.conversation_id }}'
        description: '{{ steps.correlate_parse.output.trigger }}'
        owner: observability
        settings:
          syncAlerts: true
        severity: '{{ steps.correlate_parse.output.severity }}'
        tags:
        - rca
        title: '{{ steps.correlate_parse.output.title }}'

  - name: case_id
    type: console
    with:
      message: "{% if steps.correlate_parse.output.case_id == 'NONE' %}{{ steps.create_new_case.output.id }}{% else %}{{ steps.correlate_parse.output.case_id }}{%endif%}"
  - name: add_alert_to_case
    type: kibana.request
    with:
      method: POST
      path: /api/cases/{{ steps.case_id.output }}/comments
      body:
        type: alert
        alertId: '{{ foreach.item._id }}'
        index: '{{ foreach.item._index }}'
        owner: observability
        rule:
          id: '{% if foreach.item["kibana.alert.rule.uuid"] != nil %}{{ foreach.item["kibana.alert.rule.uuid"] }}{% else %}{{ foreach.item.kibana.alert.rule.uuid }}{% endif %}'
          name: '{% if foreach.item["kibana.alert.rule.name"] != nil %}{{ foreach.item["kibana.alert.rule.name"] }}{% else %}{{ foreach.item.kibana.alert.rule.name }}{% endif %}'

  - name: add_comment_to_case
    type: kibana.request
    with:
      method: POST
      path: /api/cases/{{ steps.case_id.output }}/comments
      body:
        type: user
        owner: observability
        comment: |
          # Related Alert
          * Summary: {% if foreach.item["kibana.alert.reason"] != nil %}{{ foreach.item["kibana.alert.reason"] }}{% else %}{{ foreach.item.kibana.alert.reason }}{% endif %}
          * [Conversation](/app/agent_builder/conversations/{{ steps.correlate.output.conversation_id }})
          * Relationship to Case: {{ steps.correlate_parse.output.relation }}

  - name: queue_case
    type: elasticsearch.request
    with:
      method: POST
      path: /workflow_case_queue/_doc?refresh=wait_for
      body: '{ "case_id": "{{ steps.case_id.output }}" }'
      headers:
        Content-Type: application/json
    timeout: 30s
