consts:
  ai_connector: Elastic-Managed-LLM
  ai_proxy: 
    https://tbekiares-demo-aiassistantv2-1059491012611.us-central1.run.app
  ai_timeout: 10m
  es_host: https://snap-ae8a92.es.us-west2.gcp.elastic-cloud.com
  kbn_auth: ApiKey OEpsYkY1b0JyVktacWxPV1VITGo6Z2d2MmRZYXdTQkpOZ1dhMmVXYmo0Zw==
  kbn_host: https://snap-ae8a92.kb.us-west2.gcp.elastic-cloud.com
description: setup state for automated triage
enabled: true
name: automated_triage_setup
tags:
- automated_observability_triage
triggers:
- enabled: true
  type: manual
version: '1'
steps:
- name: delete_alert_queue
  on-failure:
    continue: true
  type: http
  with:
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    method: DELETE
    url: '{{ consts.es_host }}/workflow_alert_queue'
- name: create_alert_queue
  type: http
  with:
    body:
      mappings:
        properties:
          alerts:
            type: flattened
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    method: PUT
    url: '{{ consts.es_host }}/workflow_alert_queue'
- name: delete_case_queue
  on-failure:
    continue: true
  type: http
  with:
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    method: DELETE
    url: '{{ consts.es_host }}/workflow_case_queue'
- name: create_case_queue
  type: http
  with:
    body:
      mappings:
        properties:
          case_id:
            type: keyword
          conversation_id:
            type: keyword
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    method: PUT
    url: '{{ consts.es_host }}/workflow_case_queue'
- name: setup_cases
  on-failure:
    continue: true
  type: http
  with:
    body:
      closure_type: close-by-user
      connector:
        fields:
        id: none
        name: none
        type: .none
      customFields:
      - defaultValue: not_available
        key: workflow_execution_id
        label: workflow_execution_id
        required: false
        type: text
      - defaultValue: not_available
        key: ai_conversation_id
        label: ai_conversation_id
        required: false
        type: text
      owner: observability
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
      kbn-xsrf: true
      x-elastic-internal-origin: kibana
    method: POST
    url: '{{ consts.kbn_host }}/api/cases/configure'
- name: delete_topology
  on-failure:
    continue: true
  type: http
  with:
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    method: DELETE
    url: '{{ consts.es_host }}/workflow_topology'
- name: create_topology
  on-failure:
    continue: true
  type: http
  with:
    body:
      mappings:
        properties:
          '@timestamp':
            type: date
          system:
            type: keyword
          topology:
            type: flattened
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    method: PUT
    url: '{{ consts.es_host }}/workflow_topology'
- name: delete_config
  on-failure:
    continue: true
  type: http
  with:
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    method: DELETE
    url: '{{ consts.es_host }}/workflow_config'
- name: create_config
  type: http
  with:
    body:
      mappings:
        properties:
          workflow_id:
            type: keyword
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    method: PUT
    url: '{{ consts.es_host }}/workflow_config'
- name: get_workflows
  type: http
  with:
    body:
      limit: 20
      page: 1
      query: ''
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
      kbn-xsrf: true
      x-elastic-internal-origin: kibana
    method: POST
    url: '{{ consts.kbn_host }}/api/workflows/search'
- name: foreach_workflow
  type: foreach
  foreach: '{{ steps.get_workflows.output.data.results | json }}'
  steps:
  - name: is_case_process
    type: if
    condition: 'foreach.item.name : case_process'
    steps:
    - name: save_case_process_id
      type: http
      with:
        body:
          workflow_id: '{{ foreach.item.id }}'
        headers:
          Authorization: '{{ consts.kbn_auth }}'
          Content-Type: application/json
        method: POST
        url: '{{ consts.es_host }}/workflow_config/_doc/case_process_workflow'
  - name: is_alert_process
    type: if
    condition: 'foreach.item.name : alert_process'
    steps:
    - name: save_alert_process_id
      type: http
      with:
        body:
          workflow_id: '{{ foreach.item.id }}'
        headers:
          Authorization: '{{ consts.kbn_auth }}'
          Content-Type: application/json
        method: POST
        url: '{{ consts.es_host }}/workflow_config/_doc/alert_process_workflow'
  - name: is_not_setup_workflow
    type: if
    condition: 'not foreach.item.name : automated_triage_setup'
    steps:
    - name: get_executions
      on-failure:
        continue: true
      type: http
      with:
        headers:
          Authorization: '{{ consts.kbn_auth }}'
          Content-Type: application/json
          kbn-xsrf: true
          x-elastic-internal-origin: kibana
        method: GET
        url: '{{ consts.kbn_host }}/api/workflowExecutions?workflowId={{ foreach.item.id }}'
    - name: foreach_execution
      type: foreach
      foreach: '{{steps.get_executions.output.data.results | json}}'
      steps:
      - name: cancel_execution
        on-failure:
          continue: true
        type: http
        with:
          headers:
            Authorization: '{{ consts.kbn_auth }}'
            Content-Type: application/json
            kbn-xsrf: true
            x-elastic-internal-origin: kibana
          method: POST
          url: '{{ consts.kbn_host }}/api/workflowExecutions/{{ foreach.item.id }}/cancel'

