version: '1'
name: automated_triage_setup
description: setup state for automated triage
enabled: true
tags:
- automated_observability_triage
triggers:
- type: manual
  enabled: true
consts:
  ai_connector: Elastic-Managed-LLM
  ai_proxy: https://tbekiares-demo-aiassistantv2-1059491012611.us-central1.run.app
  ai_timeout: 10m
  es_host: https://snap2-96da6f.es.us-west2.gcp.elastic-cloud.com
  kbn_auth: ApiKey SVdFNU81b0J4Wi1oTDdBWnR5Q3I6RmhNY0pub2pwOHFwTEFfa0d4SWtldw==
  kbn_host: https://snap2-96da6f.kb.us-west2.gcp.elastic-cloud.com
steps:
- name: delete_alert_queue
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_alert_queue'
    method: DELETE
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    timeout: 30s
  on-failure:
    continue: true
- name: create_alert_queue
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_alert_queue'
    method: PUT
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    body:
      mappings:
        properties:
          alerts:
            type: flattened
    timeout: 30s
- name: delete_case_queue
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_case_queue'
    method: DELETE
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    timeout: 30s
  on-failure:
    continue: true
- name: create_case_queue
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_case_queue'
    method: PUT
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    body:
      mappings:
        properties:
          case_id:
            type: keyword
    timeout: 30s
- name: setup_cases
  type: http
  with:
    url: '{{ consts.kbn_host }}/api/cases/configure'
    method: POST
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
      kbn-xsrf: true
      x-elastic-internal-origin: kibana
    body:
      closure_type: close-by-user
      connector:
        fields:
        id: none
        name: none
        type: .none
      customFields:
      - defaultValue: not_available
        key: system
        label: system
        required: false
        type: text
      - defaultValue: not_available
        key: ai_conversation_id
        label: ai_conversation_id
        required: false
        type: text
      owner: observability
    timeout: 30s
  on-failure:
    continue: true
- name: delete_topology
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_topology'
    method: DELETE
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    timeout: 30s
  on-failure:
    continue: true
- name: create_topology
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_topology'
    method: PUT
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    body:
      mappings:
        properties:
          '@timestamp':
            type: date
          system:
            type: keyword
          topology:
            type: flattened
    timeout: 30s
  on-failure:
    continue: true
- name: delete_config
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_config'
    method: DELETE
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    timeout: 30s
  on-failure:
    continue: true
- name: create_config
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_config'
    method: PUT
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    body:
      mappings:
        properties:
          workflow_id:
            type: keyword
    timeout: 30s
- name: get_workflows
  type: http
  with:
    url: '{{ consts.kbn_host }}/api/workflows/search'
    method: POST
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
      kbn-xsrf: true
      x-elastic-internal-origin: kibana
    body:
      limit: 20
      page: 1
      query: ''
    timeout: 30s
- name: foreach_workflow
  type: foreach
  foreach: '{{ steps.get_workflows.output.data.results | json }}'
  steps:
  - name: is_case_process
    type: if
    condition: 'foreach.item.name : case_process'
    steps:
    - name: save_case_process_id
      type: http
      with:
        url: '{{ consts.es_host }}/workflow_config/_doc/case_process_workflow'
        method: POST
        headers:
          Authorization: '{{ consts.kbn_auth }}'
          Content-Type: application/json
        body:
          workflow_id: '{{ foreach.item.id }}'
        timeout: 30s
  - name: is_alert_process
    type: if
    condition: 'foreach.item.name : alert_process'
    steps:
    - name: save_alert_process_id
      type: http
      with:
        url: '{{ consts.es_host }}/workflow_config/_doc/alert_process_workflow'
        method: POST
        headers:
          Authorization: '{{ consts.kbn_auth }}'
          Content-Type: application/json
        body:
          workflow_id: '{{ foreach.item.id }}'
        timeout: 30s

