name: build_topologies
enabled: true
version: '1'
description: build topology to help with correlation and RCA
tags:
- rca
settings:
  timeout: 20m
triggers:
- type: manual
- type: scheduled
  with:
    every: 30m
steps:

- name: get_topologies
  type: onechat.runAgent
  with:
    agent_id: topology_builder
    message: "get system topologies from {{ 'now' | date: '%s' | minus: 3600 | date: '%Y-%m-%dT%H:%M:%SZ' }} to {{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}"

- name: get_topologies_parsed
  type: console
  with:
    message: ${{steps.get_topologies.output | json_parse}}

- name: foreach_topology
  type: foreach
  foreach: '{{ steps.get_topologies_parsed.output }}'
  steps:
  - name: debug
    type: console
    with:
      message: "{{ foreach.item['system_environment']}}"

  - name: store_topology
    type: elasticsearch.request
    with:
      method: POST
      path: /workflow_topology/_doc
      body: '{{ foreach.item | json }}'
      headers:
        Content-Type: application/json
