name: case_dequeue
description: dequeue cases serially and start processing
enabled: true
tags:
- automated_observability_triage
triggers:
- type: manual
  enabled: true
consts:
  ai_connector: Elastic-Managed-LLM
  ai_proxy: https://tbekiares-demo-aiassistantv2-1059491012611.us-central1.run.app
  ai_timeout: 10m
  es_host: https://snap2-96da6f.es.us-west2.gcp.elastic-cloud.com
  kbn_auth: ApiKey SVdFNU81b0J4Wi1oTDdBWnR5Q3I6RmhNY0pub2pwOHFwTEFfa0d4SWtldw==
  kbn_host: https://snap2-96da6f.kb.us-west2.gcp.elastic-cloud.com
steps:
- name: get_case_process_id
  type: http
  with:
    url: '{{ consts.es_host }}/workflow_config/_doc/case_process_workflow'
    method: GET
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
    timeout: 30s
- name: case_process_status
  type: http
  with:
    url: '{{ consts.kbn_host }}/api/workflowExecutions?workflowId={{ steps.get_case_process_id.output.data._source.workflow_id}}'
    method: GET
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
      kbn-xsrf: true
      x-elastic-internal-origin: kibana
    timeout: 30s
- name: is_case_process_running
  type: if
  condition: 'steps.case_process_status.output.status : completed'
  steps:
  - name: is_case_process_running_debug1
    type: console
    with:
      message: workflow_alert_process running
  else:
  - name: is_case_process_running_debug2
    type: console
    with:
      message: workflow_alert_process not running
  - name: dequeue_case
    type: http
    with:
      url: '{{ consts.es_host }}/workflow_case_queue/_search'
      method: GET
      headers:
        Authorization: '{{ consts.kbn_auth }}'
        Content-Type: application/json
      body:
        _source: true
        query:
          match_all:
        size: 1
      timeout: 30s
  - name: start_case_process
    type: http
    with:
      url: '{{ consts.kbn_host }}/api/workflows/{{ steps.get_case_process_id.output.data._source.workflow_id}}/run'
      method: POST
      headers:
        Authorization: '{{ consts.kbn_auth }}'
        Content-Type: application/json
        kbn-xsrf: true
        x-elastic-internal-origin: kibana
      body: '{ "inputs": {"case_id": {{steps.dequeue_case.output.data.hits.hits[0]._source.case_id }} } }'
      timeout: 30s
  - name: mark_case_handled
    type: http
    with:
      url: '{{ consts.es_host }}/workflow_case_queue/_doc/{{steps.dequeue_case.output.data.hits.hits[0]._id}}'
      method: DELETE
      headers:
        Authorization: '{{ consts.kbn_auth }}'
        Content-Type: application/json
      timeout: 30s
