name: case_process
enabled: true
description: Perform RCA on a Case
tags:
- rca
triggers:
- type: manual
settings:
  timeout: 20m
inputs:
- name: case_id
  type: string
steps:
- name: rca
  type: kibana.request
  with:
    method: POST
    path: /api/agent_builder/converse
    headers:
      kbn-xsrf: 'true'
    body:
      agent_id: rca
      input: 'perform RCA on this case: {{ inputs.case_id }}'

- name: foreach_steps
  type: foreach
  foreach: '{{ steps.rca.output.steps }}'
  steps:
  - name: if_reasoning
    type: if
    condition: 'foreach.item.type: "reasoning"'
    steps:
    - name: add_reasoning_to_existing_case
      type: kibana.request
      with:
        method: POST
        path: /api/cases/{{ inputs.case_id }}/comments
        body:
          type: user
          owner: observability
          comment: 🤔 {{ foreach.item.reasoning }}

- name: add_response_to_existing_case
  type: kibana.request
  with:
    method: POST
    path: /api/cases/{{ inputs.case_id }}/comments
    body:
      type: user
      owner: observability
      comment: '{{ steps.rca.output.response.message }}'

- name: add_conversation_to_existing_case
  type: kibana.request
  with:
    method: POST
    path: /api/cases/{{ inputs.case_id }}/comments
    body:
      type: user
      owner: observability
      comment: 🔍 You can continue your investigation or take remediation action [here](/app/agent_builder/conversations/{{ steps.rca.output.conversation_id }}).






