name: case_process
enabled: true
description: Perform RCA on a Case
tags:
- rca
triggers:
- type: manual
settings:
  timeout: 20m
inputs:
- name: case_id
  type: string
steps:

- name: get_case
  type: kibana.request
  with:
    method: GET
    path: /api/cases/{{ inputs.case_id }}

- name: get_ai_coversation_id
  type: console
  with:
    message: "{% for field in steps.get_case.output.customFields %}{%- if field.key == 'ai_conversation_id' -%}{{ field.value }}{% break %}{%- endif -%}{% endfor %}"

- name: rca
  type: kibana.request
  with:
    method: POST
    path: /api/agent_builder/converse
    headers:
      kbn-xsrf: 'true'
    body: |
      {
        "agent_id": "rca",
        "input": "perform RCA on case id: {{ inputs.case_id }}"
        {% if steps.get_ai_coversation_id.output != "not_available" %},"conversation_id": "{{ steps.get_ai_coversation_id.output }}"{% endif %}
      }

- name: foreach_steps
  type: foreach
  foreach: '{{ steps.rca.output.steps }}'
  steps:
  - name: if_reasoning
    type: if
    condition: 'foreach.item.type: "reasoning"'
    steps:
    - name: add_reasoning_to_existing_case
      type: kibana.request
      with:
        method: POST
        path: /api/cases/{{ inputs.case_id }}/comments
        body:
          type: user
          owner: observability
          comment: 🤔 {{ foreach.item.reasoning }}

- name: get_case_refresh
  type: kibana.request
  with:
    method: GET
    path: /api/cases/{{ inputs.case_id }}

- name: update_ai_conversation_id
  type: kibana.request
  with:
    method: PATCH
    path: /api/cases
    body:
      cases:
      - id: '{{ inputs.case_id }}'
        version: '{{ steps.get_case_refresh.output.version }}'
        customFields:
        - key: ai_conversation_id
          type: text
          value: '{{ steps.rca.output.conversation_id }}'
  on-failure:
    continue: true

- name: add_response_to_existing_case
  type: kibana.request
  with:
    method: POST
    path: /api/cases/{{ inputs.case_id }}/comments
    body:
      type: user
      owner: observability
      comment: '{{ steps.rca.output.response.message }}'

- name: add_conversation_to_existing_case
  type: kibana.request
  with:
    method: POST
    path: /api/cases/{{ inputs.case_id }}/comments
    body:
      type: user
      owner: observability
      comment: 🔍 You can continue your investigation or take remediation action [here](/app/agent_builder/conversations/{{ steps.rca.output.conversation_id }}).






