consts:
  ai_connector: Elastic-Managed-LLM
  ai_proxy: 
    https://tbekiares-demo-aiassistantv2-1059491012611.us-central1.run.app
  ai_timeout: 10m
  es_host: https://snap-ae8a92.es.us-west2.gcp.elastic-cloud.com
  kbn_auth: ApiKey OEpsYkY1b0JyVktacWxPV1VITGo6Z2d2MmRZYXdTQkpOZ1dhMmVXYmo0Zw==
  kbn_host: https://snap-ae8a92.kb.us-west2.gcp.elastic-cloud.com
description: dequeue cases serially and start processing
enabled: true
name: case_dequeue
tags:
- automated_observability_triage
triggers:
- type: manual
steps:
- name: get_case_process_id
  type: http
  with:
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
    method: GET
    timeout: 30s
    url: '{{ consts.es_host }}/workflow_config/_doc/case_process_workflow'
- name: case_process_status
  type: http
  with:
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
      kbn-xsrf: true
      x-elastic-internal-origin: kibana
    method: GET
    url: '{{ consts.kbn_host }}/api/workflowExecutions?workflowId={{ steps.get_case_process_id.output.data._source.workflow_id}}'
- name: is_case_process_running
  type: if
  condition: 'steps.case_process_status.output.status : completed'
  steps:
  - name: is_case_process_running_debug1
    type: console
    with:
      message: workflow_alert_process running
  else:
  - name: is_case_process_running_debug2
    type: console
    with:
      message: workflow_alert_process not running
  - name: dequeue_case
    type: http
    with:
      body:
        _source: true
        query:
          match_all:
        size: 1
      headers:
        Authorization: '{{ consts.kbn_auth }}'
        Content-Type: application/json
      method: GET
      url: '{{ consts.es_host }}/workflow_case_queue/_search'
  - name: start_case_process
    type: http
    with:
      body: '{ "inputs": {"event": {{steps.dequeue_case.output.data.hits.hits[0]._source
        | json }} } }'
      headers:
        Authorization: '{{ consts.kbn_auth }}'
        Content-Type: application/json
        kbn-xsrf: true
        x-elastic-internal-origin: kibana
      method: POST
      url: '{{ consts.kbn_host }}/api/workflows/{{ steps.get_case_process_id.output.data._source.workflow_id}}/run'
  - name: mark_case_handled
    type: http
    with:
      headers:
        Authorization: '{{ consts.kbn_auth }}'
        Content-Type: application/json
      method: DELETE
      url: '{{ consts.es_host }}/workflow_case_queue/_doc/{{steps.dequeue_case.output.data.hits.hits[0]._id}}'

