consts:
  ai_connector: Elastic-Managed-LLM
  ai_proxy: 
    https://tbekiares-demo-aiassistantv2-1059491012611.us-central1.run.app
  ai_timeout: 10m
  es_host: https://snap-ae8a92.es.us-west2.gcp.elastic-cloud.com
  kbn_auth: ApiKey OEpsYkY1b0JyVktacWxPV1VITGo6Z2d2MmRZYXdTQkpOZ1dhMmVXYmo0Zw==
  kbn_host: https://snap-ae8a92.kb.us-west2.gcp.elastic-cloud.com
name: case_process
version: '1'
description: Process o11y cases
enabled: true
tags:
- automated_observability_triage
triggers:
- enabled: true
  type: manual
inputs:
- name: case_id
  type: string
- default: ''
  name: conversation_id
  type: string
- default: 0
  name: start_at_step
  type: number
- default: 2
  name: stop_at_step
  type: number
steps:
- name: debug2
  type: console
  with:
    message: '{{ inputs | json }}'
- name: get_case_process_id
  type: http
  with:
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    method: GET
    url: '{{ consts.es_host }}/workflow_config/_doc/case_process_workflow'
- name: get_case
  type: kibana.request
  with:
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    method: GET
    path: /api/cases/{{ inputs.case_id }}
- name: get_case_alerts
  type: kibana.request
  with:
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    method: GET
    path: /api/cases/{{ inputs.case_id }}/alerts
- name: debug3
  type: console
  with:
    message: '{{ steps.get_case_alerts.output | json }}'
- name: get_case_comments
  type: kibana.request
  with:
    headers:
      Authorization: '{{ consts.kbn_auth }}'
    method: GET
    path: /api/cases/{{ inputs.case_id }}/comments/_find
- name: debug1
  type: console
  with:
    message: '{{ steps.get_case.output | json }}'
- name: get_topology
  type: http
  with:
    body:
      aggs:
        unique_field_buckets:
          aggs:
            latest_document:
              top_hits:
                _source:
                  includes:
                  - system
                  - topology
                size: 1
                sort:
                - '@timestamp':
                  order: desc
          terms:
            field: system.keyword
            size: 100
      size: 0
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
    method: GET
    url: '{{ consts.es_host }}/workflow_topology/_search'
- name: exec_test_1_start
  type: if
  condition: inputs.start_at_step <= 1
  steps:
  - name: rca1
    type: http
    with:
      body:
        connectorId: '{{ consts.ai_connector }}'
        messages:
        - '@timestamp': now
          message:
            content: |
              "We will be performing a multi-step Root Cause Analysis. 
              During your analysis, use the provided incident/case, consider the alerts attached to the case and any comments in the case, and the attached topology to understand dependencies. 
              When looking for problems, always start at the service which is closest to or is a leaf node and is alerting. 
              Do not start the RCA analysis; we will be doing it together step-by-step.
              First, can you identify the service from the topology which is both closet to being a leaf node AND has an active alert associated with it? 
              Additionally, what is a good time window to search for problems before and after the associated active alert?
              <case>
                {{ steps.get_case.output | json }}
              </case>
              <alerts>
                {{ steps.get_case_alerts.output | json }}
              </alerts>
              <comments>
                {{ steps.get_case_comments.output | json }}
              </comments>
              <topology> 
                {{ steps.get_topology.output.data.hits.hits | json }}
              </topology>"
            role: user
        output: false
        persist: true
      headers:
        Content-Type: application/json
        kibana-auth: '{{ consts.kbn_auth }}'
        kibana-host: '{{ consts.kbn_host }}'
      method: POST
      timeout: '{{ consts.ai_timeout }}'
      url: '{{ consts.ai_proxy }}/api/observability_ai_assistant/chat/complete'
- name: exec_test_2_start
  type: if
  condition: inputs.start_at_step <= 2 and inputs.stop_at_step > 2
  steps:
  - name: rca2
    type: http
    with:
      body:
        connectorId: '{{ consts.ai_connector }}'
        conversationId: '{{ inputs.conversation_id }}'
        messages:
        - '@timestamp': now
          message:
            content: |
              "Second, look at the logs for the identified service with the recommended time window. 
              In particular, focus on logs with warning, error, or fatal severity. 
              Does the log rate or log content suggest a problem?"
            role: user
        output: false
        persist: true
      headers:
        Content-Type: application/json
        kibana-auth: '{{ consts.kbn_auth }}'
        kibana-host: '{{ consts.kbn_host }}'
      method: POST
      timeout: '{{ consts.ai_timeout }}'
      url: '{{ consts.ai_proxy }}/api/observability_ai_assistant/chat/complete'
  else:
  - name: exec_test_2_stop
    type: if
    condition: 'inputs.stop_at_step : 2'
    steps:
    - name: start_case_process2
      type: http
      with:
        body:
          inputs:
            case_id: '{{ inputs.case_id }}'
            conversation_id: '{{ steps.rca1.output.data.conversationId }}'
            start_at_step: 2
            stop_at_step: 3
        headers:
          Authorization: '{{ consts.kbn_auth }}'
          Content-Type: application/json
          kbn-xsrf: true
          x-elastic-internal-origin: kibana
        method: POST
        url: '{{ consts.kbn_host }}/api/workflows/{{ steps.get_case_process_id.output.data._source.workflow_id }}/run'

- name: exec_test_3_start
  type: if
  condition: inputs.start_at_step <= 3 and inputs.stop_at_step > 3
  steps:
  - name: rca3
    type: http
    with:
      body:
        connectorId: '{{ consts.ai_connector }}'
        conversationId: '{{ inputs.conversation_id }}'
        messages:
        - '@timestamp': now
          message:
            content: |
              "Third, look at the metrics for the identified service with the recommended time window. 
              Is there anything in the metric data that would suggest a problem?"
            role: user
        output: false
        persist: true
      headers:
        Content-Type: application/json
        kibana-auth: '{{ consts.kbn_auth }}'
        kibana-host: '{{ consts.kbn_host }}'
      method: POST
      timeout: '{{ consts.ai_timeout }}'
      url: '{{ consts.ai_proxy }}/api/observability_ai_assistant/chat/complete'
  else:
  - type: if
    name: exec_test_3_stop
    condition: 'inputs.stop_at_step : 3'
    steps:
    - name: start_case_process3
      type: http
      with:
        body:
          inputs:
            case_id: '{{ inputs.case_id }}'
            conversation_id: '{{ inputs.conversation_id }}'
            start_at_step: 3
            stop_at_step: 4
        headers:
          Authorization: '{{ consts.kbn_auth }}'
          Content-Type: application/json
          kbn-xsrf: true
          x-elastic-internal-origin: kibana
        method: POST
        url: '{{ consts.kbn_host }}/api/workflows/{{ steps.get_case_process_id.output.data._source.workflow_id }}/run'

- name: exec_test_4_start
  type: if
  condition: inputs.start_at_step <= 4 and inputs.stop_at_step > 4
  steps:
  - name: rca4
    type: http
    with:
      body:
        connectorId: '{{ consts.ai_connector }}'
        conversationId: '{{ inputs.conversation_id }}'
        messages:
        - '@timestamp': now
          message: 
            content: |
              "Fourth, look at the traces for the identified service with the recommended time window. 
              Look in particular for failed traces and associated exceptions. 
              Is there anything in the trace data that would suggest a problem?"
            role: user
        output: false
        persist: true
      headers:
        Content-Type: application/json
        kibana-auth: '{{ consts.kbn_auth }}'
        kibana-host: '{{ consts.kbn_host }}'
      method: POST
      timeout: '{{ consts.ai_timeout }}'
      url: '{{ consts.ai_proxy }}/api/observability_ai_assistant/chat/complete'
  else:
  - name: exec_test_4_stop
    type: if
    condition: 'inputs.stop_at_step : 4'
    steps:
    - name: start_case_process4
      type: http
      with:
        body:
          inputs:
            case_id: '{{ inputs.case_id }}'
            conversation_id: '{{ inputs.conversation_id }}'
            start_at_step: 4
            stop_at_step: 5
        headers:
          Authorization: '{{ consts.kbn_auth }}'
          Content-Type: application/json
          kbn-xsrf: true
          x-elastic-internal-origin: kibana
        method: POST
        url: '{{ consts.kbn_host }}/api/workflows/{{ steps.get_case_process_id.output.data._source.workflow_id}}/run'

- name: exec_test_5_start
  type: if
  condition: inputs.start_at_step <= 5 and inputs.stop_at_step > 5
  steps:
  - name: rca5
    type: http
    with:
      body:
        connectorId: '{{ consts.ai_connector }}'
        conversationId: '{{ inputs.conversation_id }}'
        messages:
        - '@timestamp': now
          message:
            content: "Considering the provided topology, the analysis, and the attached alerts, please output a detailed Root Cause Analysis in a field called 'rca'."
            role: user
        output: true
        persist: true
      headers:
        Content-Type: application/json
        kibana-auth: '{{ consts.kbn_auth }}'
        kibana-host: '{{ consts.kbn_host }}'
      method: POST
      timeout: '{{ consts.ai_timeout }}'
      url: '{{ consts.ai_proxy }}/api/observability_ai_assistant/chat/complete'
  - name: add_comment_to_existing_case
    type: kibana.request
    with:
      body:
        comment: '{{ steps.rca5.output.data.output.rca }}'
        owner: observability
        type: user
      headers:
        Authorization: '{{ consts.kbn_auth }}'
        Content-Type: application/json
        kbn-xsrf: true
      method: POST
      path: /api/cases/{{ inputs.case_id }}/comments
  - name: add_conversation_to_existing_case
    type: kibana.request
    with:
      body:
        comment: You can continue your investigation [here](/app/observabilityAIAssistant/conversations/{{ inputs.conversation_id }}).
        owner: observability
        type: user
      headers:
        Authorization: '{{ consts.kbn_auth }}'
        Content-Type: application/json
        kbn-xsrf: true
      method: POST
      path: /api/cases/{{ inputs.case_id }}/comments
  
  else:
  - name: exec_test_5_stop
    type: if
    condition: 'inputs.stop_at_step : 5'
    steps:
    - name: start_case_process5
      type: http
      with:
        body:
          inputs:
            case_id: '{{ inputs.case_id }}'
            conversation_id: '{{ inputs.conversation_id }}'
            start_at_step: 5
            stop_at_step: 6
        headers:
          Authorization: '{{ consts.kbn_auth }}'
          Content-Type: application/json
          kbn-xsrf: true
          x-elastic-internal-origin: kibana
        method: POST
        url: '{{ consts.kbn_host }}/api/workflows/{{ steps.get_case_process_id.output.data._source.workflow_id }}/run'

