version: '1'
name: get_service_map
description: Get Service Map
enabled: true
tags:
- rca
triggers:
- type: manual
inputs:
- name: search_start_time
  description: the start of the time window
  type: string
- name: search_end_time
  description: the end of the time window
  type: string
- name: service_environment
  description: Service Environment
  default: ENVIRONMENT_ALL
  type: string
steps:
- name: get_service_map
  type: kibana.request
  with:
    method: GET
    path: /internal/apm/service-map?start={{ inputs.search_start_time }}&end={{ inputs.search_end_time }}&environment={{ inputs.service_environment }}&serviceGroup=&kuery=
    headers:
      x-elastic-internal-origin: kibana
