version: '1'
name: test_workflow
enabled: true
triggers:
- type: manual
inputs:
- name: user_name
  type: string
steps:
- name: first-step
  type: console
  with:
    message: Hello {{ inputs.user_name }}
- name: get_www
  type: http
  with:
    url: https://elastic.co
    method: GET
    headers: {}
  timeout: 5s
  on-failure:
    fallback:
    - name: debug
      type: console
      with:
        message: http call failed
- name: store_www
  type: elasticsearch.request
  with:
    method: POST
    path: test_index/_doc
    body:
      content: '{{ steps.get_www.output.data }}'
