consts:
  ai_connector: Elastic-Managed-LLM
  ai_proxy: https://tbekiares-demo-aiassistantv2-1059491012611.us-central1.run.app
  ai_timeout: 10m
  es_host: https://snap2-96da6f.es.us-west2.gcp.elastic-cloud.com
  kbn_auth: ApiKey SVdFNU81b0J4Wi1oTDdBWnR5Q3I6RmhNY0pub2pwOHFwTEFfa0d4SWtldw==
  kbn_host: https://snap2-96da6f.kb.us-west2.gcp.elastic-cloud.com
  topology_lookback_time: 1h
name: topology
enabled: true
version: '1'
description: build topology to help with correlation and RCA
tags:
- automated_observability_triage
settings:
  timeout: 20m
triggers:
- enabled: true
  type: scheduled
  with:
    every: 1h
steps:
- name: get_end_time
  type: http
  with:
    body:
      query: ROW current_date = NOW()
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
    method: POST
    url: '{{ consts.es_host }}/_query'
- name: get_start_time
  type: http
  with:
    body:
      query: ROW current_date = NOW() - {{ consts.topology_lookback_time }}
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
    method: POST
    url: '{{ consts.es_host }}/_query'
- name: get_service_map
  type: http
  with:
    headers:
      Authorization: '{{ consts.kbn_auth }}'
      Content-Type: application/json
      kbn-xsrf: true
      x-elastic-internal-origin: kibana
    method: GET
    url: '{{ consts.kbn_host }}/internal/apm/service-map?start={{ steps.get_start_time.output.data.values[0] }}&end={{ steps.get_end_time.output.data.values[0] }}&environment=ENVIRONMENT_ALL&serviceGroup=&kuery='

- name: get_topology1
  type: http
  with:
    body:
      connectorId: '{{ consts.ai_connector }}'
      persist: false
      instructions:
        - Output a field 'topologies' which is an array of topology objects, with each object having a field 'system' which is the system the topology is applicable to and a field 'topology' which is a JSON object in node-link format.
        - A system is defined by a namespace.
        - Only consider observability data from the previous hour.
      messages:
      - '@timestamp': now
        message:
          content: |
            "We will use a multi-step process to build a topology. First, build a topology from the attached service_map.
            <service_map>
              {{ steps.get_service_map.output.data | json }}
            </service_map>"
          role: user
    headers:
      Content-Type: application/json
      kibana-auth: '{{ consts.kbn_auth }}'
      kibana-host: '{{ consts.kbn_host }}'
    method: POST
    timeout: '{{ consts.ai_timeout }}'
    url: '{{ consts.ai_proxy }}/api/observability_ai_assistant/chat/complete'

- name: get_topology2
  type: http
  with:
    body:
      connectorId: '{{ consts.ai_connector }}'
      persist: false
      conversationHistory: '{{ steps.get_topology1.output.data.conversationHistory | json }}'
      retries: 1
      instructions:
        - Output a field 'topologies' which is an array of topology objects, with each object having a field 'system' which is the system the topology is applicable to and a field 'topology' which is a JSON object in node-link format.
        - A system is defined by a namespace.
        - Only consider observability data from the previous hour.
      messages:
      - '@timestamp': now
        message:
          content: |
            "Next, examine only log data to determine if any proxies exist between services. If they do, augment the topology from the previous step with any proxies discovered."
          role: user
    headers:
      Content-Type: application/json
      kibana-auth: '{{ consts.kbn_auth }}'
      kibana-host: '{{ consts.kbn_host }}'
    method: POST
    timeout: '{{ consts.ai_timeout }}'
    url: '{{ consts.ai_proxy }}/api/observability_ai_assistant/chat/complete'

- name: get_topology3
  type: http
  with:
    body:
      connectorId: '{{ consts.ai_connector }}'
      persist: false
      conversationHistory: '{{ steps.get_topology2.output.data.conversationHistory | json }}'
      retries: 1
      instructions:
        - Output a field 'topologies' which is an array of topology objects, with each object having a field 'system' which is the system the topology is applicable to and a field 'topology' which is a JSON object in node-link format.
        - A system is defined by a namespace.
        - Only consider observability data from the previous hour.
      messages:
      - '@timestamp': now
        message:
          content: |
            "Next, for each node in each topology, add an additional field 'host.name' which is the hostname of the VM or kubernetes node or machine on which the service is running. This can be obtained by searching 'traces-*,logs-*,metrics-*' for 'resource.attributes.host.name' for a given 'service.name', where 'service.name' is the 'id' of the node in the topology."
          role: user
    headers:
      Content-Type: application/json
      kibana-auth: '{{ consts.kbn_auth }}'
      kibana-host: '{{ consts.kbn_host }}'
    method: POST
    timeout: '{{ consts.ai_timeout }}'
    url: '{{ consts.ai_proxy }}/api/observability_ai_assistant/chat/complete'

- name: foreach_system
  type: foreach
  foreach: '{{ steps.get_topology3.output.data.result.topologies | json }}'
  steps:
  - name: store_topology
    type: http
    with:
      body: '{"@timestamp":"{{ steps.get_end_time.output.data.values[0] }}", "system":"{{ foreach.item.system }}", "topology": {{ foreach.item.topology | json }} }'
      headers:
        Authorization: '{{ consts.kbn_auth }}'
        Content-Type: application/json
      method: POST
      timeout: 30s
      url: '{{ consts.es_host }}/workflow_topology/_doc'