apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpuhog
  namespace: $NAMESPACE
  labels:
    app: trading
    service: cpuhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading
      service: cpuhog
  template:
    metadata:
      labels:
        app: trading
        service: cpuhog
    spec:
      containers:
        - name: cpuhog
          image: $REPO/cpuhog:$COURSE
          imagePullPolicy: Always
      restartPolicy: Always