name: alert_handler
enabled: true
description: Perform RCA on alerts
tags:
- rca-core
triggers:
- type: alert
steps:
- name: foreach_alert
  type: foreach
  foreach: '{{ event.alerts }}'
  steps:
    - name: state
      type: if
      condition: 'foreach.item.kibana.alert.status: "recovered"'
      steps:
        - name: get_cases
          type: kibana.request
          with:
            headers:
              x-elastic-internal-origin: kibana
            method: GET
            path: /api/cases/_find?status=open&tags=auto
        - name: foreach_case
          type: foreach
          foreach: '{{ steps.get_cases.output.cases }}'
          steps:
            - name: get_case_alerts
              type: kibana.request
              with:
                method: GET
                path: /api/cases/{{ foreach.item.id }}/alerts
            - name: foreach_case_alert
              type: foreach
              foreach: '{{ steps.get_case_alerts.output }}'
              steps:
                - name: is_alert
                  type: if
                  condition: 'foreach.item.id: {{ steps.foreach_alert.item._id }}'
                  steps:
                    - name: comment
                      type: cases.addComment
                      with:
                        case_id: '{{ steps.foreach_case.item.id }}'
                        comment: "automatically closing case because related alert recovered"
                    - name: close_case
                      type: cases.closeCase
                      with:
                        case_id: '{{ steps.foreach_case.item.id }}'
                      on-failure:
                        continue: true
      else:
        - name: rca
          type: ai.agent
          create-conversation: true
          connector-id: Anthropic-Claude-Sonnet-4-6
          with:
            message: |
              Perform Root Cause Analysis on this alert, create a case with the result of the analysis (tag the case with 'auto'), and attach the alert.
              ```json
              {{ foreach.item | json: 2 }}
              ```
