---
apiVersion: v1
kind: Service
metadata:
  name: wiki-ext
  namespace: wiki
spec:
  ports:
    - name: wiki
      port: 9082
      protocol: TCP
      targetPort: http
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: wiki
    app.kubernetes.io/name: wiki
---
