gcloud compute instances create tbekiares-kestra \
    --project=elastic-sa \
    --zone=us-central1-f \
    --machine-type=n2-standard-4 \
    --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default \
    --maintenance-policy=MIGRATE \
    --provisioning-model=STANDARD \
    --service-account=1059491012611-compute@developer.gserviceaccount.com \
    --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/trace.append \
    --create-disk=auto-delete=yes,boot=yes,device-name=tbekiares-kestra,image=projects/debian-cloud/global/images/debian-12-bookworm-v20251111,mode=rw,size=100,type=pd-balanced \
    --no-shielded-secure-boot \
    --shielded-vtpm \
    --shielded-integrity-monitoring \
    --labels=division=field,org=sa,team=pura,project=tyronebekiares,keep-until=2025-12-20,goog-ec-src=vm_add-gcloud \
    --reservation-affinity=any